### PR TITLE
Update to Recent version of ddms

### PR DESCRIPTION
**Pull request by ramapalani**
Converter was not working when newer ddms library was present.
Error I got was:
`java.lang.AbstractMethodError: Method de/preusslerpark/android/tools/Converter$1.testIgnored(Lcom/android/ddmlib/testrunner/TestIdentifier;)V is abstract`

So updated ddms to newer version (primarily to updated method signatures of overridden/abstract method) 

@dpreussler Can you review this PR?

### CODE REVIEW

**Review by dpreussler — APPROVED** [review]

**Comment by dpreussler** [comment]
thanks for fixing this

**Comment by dpreussler** [comment]
I'll try to create release later... normally takes at least 24h before visible on mavencentral

**Comment by ramapalani** [comment]
@dpreussler Thanks for merging this PR
Can you let me know the new version of the jar.

**Comment by dpreussler** [comment]
https://search.maven.org/artifact/de.jodamob.android/automator-log-converter/1.6.0-1-g46e78e3/jar

**Pull request merged**
