### PR TITLE
Fixed README.md usage instructions

### PR DESCRIPTION
**Pull request by ohadschn**

### CODE REVIEW

**Comment by cnishina** [comment]
Doh this is my mistake. There are two options to the fix... since this is your project, I'll let you pick the 

* Fix the `README.md` and remove "convert" and change the `Runner.java` usage text from `"usage: convert <filename>"` to `"usage: <filename>"`
* Change the `Runner.java` file to check for a minimum args length of 2 and require the word "convert" as `args[0]`.

@dpreussler what do you think?

**Comment by ohadschn** [comment]
Well the tool has "convert" in the name so I really think the verb is redundant...

**Comment by cnishina** [comment]
It does appear redundant. Add the fix to `Runner.java` and add that to your pull request.

**Comment by ohadschn** [comment]
You mean like this?

**Comment by cnishina** [comment]
Nicely done @ohadschn. Thanks for fixing my mistake.

**Comment by ohadschn** [comment]
I would hardly call it a mistake - a typo at most ;)

**Comment by dpreussler** [comment]
thanks guys!

**Comment by ohadschn** [comment]
You got it, thanks for merging!

**Pull request merged**
